{"daring": [
	{"index": 0,"time": 25,"type": "word","value": "9.","element": "narrate-6-quiz-9"},
	{"index": 2,"time": 1267,"type": "word","value": "Should","element": "narrate-6-quiz-9"},
	{"index": 3,"time": 1480,"type": "word","value": "you","element": "narrate-6-quiz-9"},
	{"index": 4,"time": 1617,"type": "word","value": "engage","element": "narrate-6-quiz-9"},
	{"index": 5,"time": 2042,"type": "word","value": "with","element": "narrate-6-quiz-9"},
	{"index": 6,"time": 2205,"type": "word","value": "a","element": "narrate-6-quiz-9"},
	{"index": 7,"time": 2242,"type": "word","value": "pop-up","element": "narrate-6-quiz-9"},
	{"index": 8,"time": 2730,"type": "word","value": "on","element": "narrate-6-quiz-9"},
	{"index": 9,"time": 2855,"type": "word","value": "your","element": "narrate-6-quiz-9"},
	{"index": 10,"time": 2955,"type": "word","value": "screen","element": "narrate-6-quiz-9"},
	{"index": 11,"time": 3342,"type": "word","value": "that","element": "narrate-6-quiz-9"},
	{"index": 12,"time": 3517,"type": "word","value": "claims","element": "narrate-6-quiz-9"},
	{"index": 13,"time": 3892,"type": "word","value": "you","element": "narrate-6-quiz-9"},
	{"index": 14,"time": 3980,"type": "word","value": "have","element": "narrate-6-quiz-9"},
	{"index": 15,"time": 4155,"type": "word","value": "only","element": "narrate-6-quiz-9"},
	{"index": 16,"time": 4392,"type": "word","value": "10 seconds","element": "narrate-6-quiz-9"},
	{"index": 17,"time": 5130,"type": "word","value": "to","element": "narrate-6-quiz-9"},
	{"index": 18,"time": 5217,"type": "word","value": "win","element": "narrate-6-quiz-9"},
	{"index": 19,"time": 5342,"type": "word","value": "a","element": "narrate-6-quiz-9"},
	{"index": 20,"time": 5392,"type": "word","value": "free","element": "narrate-6-quiz-9"},
	{"index": 21,"time": 5642,"type": "word","value": "tablet","element": "narrate-6-quiz-9"},

	{"index": 25,"time": 7915,"type": "word","value": "The","element": "narrate-6-quiz-9"},
	{"index": 26,"time": 8015,"type": "word","value": "pop-up","element": "narrate-6-quiz-9"},
	{"index": 27,"time": 8490,"type": "word","value": "says","element": "narrate-6-quiz-9"},
	{"index": 28,"time": 8802,"type": "word","value": "iPhone","element": "narrate-6-quiz-9"},
	{"index": 29,"time": 9240,"type": "word","value": "14","element": "narrate-6-quiz-9"},
	{"index": 30,"time": 9752,"type": "word","value": "Tester","element": "narrate-6-quiz-9"},

	{"index": 31,"time": 10832,"type": "word","value": "Congratulations","element": "narrate-6-quiz-9"},

	{"index": 32,"time": 12500,"type": "word","value": "YOU","element": "narrate-6-quiz-9"},
	{"index": 33,"time": 12625,"type": "word","value": "HAVE","element": "narrate-6-quiz-9"},
	{"index": 34,"time": 12787,"type": "word","value": "BEEN","element": "narrate-6-quiz-9"},
	{"index": 35,"time": 12937,"type": "word","value": "SELECTED","element": "narrate-6-quiz-9"},
	{"index": 36,"time": 13412,"type": "word","value": "TO","element": "narrate-6-quiz-9"},
	{"index": 37,"time": 13537,"type": "word","value": "GET","element": "narrate-6-quiz-9"},
	{"index": 38,"time": 13725,"type": "word","value": "OUR","element": "narrate-6-quiz-9"},
	{"index": 39,"time": 13862,"type": "word","value": "EXCLUSIVE","element": "narrate-6-quiz-9"},
	{"index": 40,"time": 14412,"type": "word","value": "REWARD","element": "narrate-6-quiz-9"},

	{"index": 41,"time": 15430,"type": "word","value": "You","element": "narrate-6-quiz-9"},
	{"index": 42,"time": 15555,"type": "word","value": "simply","element": "narrate-6-quiz-9"},
	{"index": 43,"time": 15955,"type": "word","value": "need","element": "narrate-6-quiz-9"},
	{"index": 44,"time": 16192,"type": "word","value": "to","element": "narrate-6-quiz-9"},
	{"index": 45,"time": 16305,"type": "word","value": "answer","element": "narrate-6-quiz-9"},
	{"index": 46,"time": 16730,"type": "word","value": "a","element": "narrate-6-quiz-9"},
	{"index": 47,"time": 16780,"type": "word","value": "few","element": "narrate-6-quiz-9"},
	{"index": 48,"time": 17005,"type": "word","value": "Quick","element": "narrate-6-quiz-9"},
	{"index": 49,"time": 17292,"type": "word","value": "questions","element": "narrate-6-quiz-9"},
	{"index": 50,"time": 17742,"type": "word","value": "regarding","element": "narrate-6-quiz-9"},
	{"index": 51,"time": 18180,"type": "word","value": "your","element": "narrate-6-quiz-9"},
	{"index": 52,"time": 18342,"type": "word","value": "experience","element": "narrate-6-quiz-9"},
	{"index": 53,"time": 19030,"type": "word","value": "with","element": "narrate-6-quiz-9"},
	{"index": 54,"time": 19205,"type": "word","value": "us","element": "narrate-6-quiz-9"},
	{"index": 55,"time": 19392,"type": "word","value": "to","element": "narrate-6-quiz-9"},
	{"index": 56,"time": 19480,"type": "word","value": "get","element": "narrate-6-quiz-9"},
	{"index": 57,"time": 19642,"type": "word","value": "a","element": "narrate-6-quiz-9"},
	{"index": 58,"time": 19705,"type": "word","value": "brand-new","element": "narrate-6-quiz-9"},

	{"index": 60,"time": 20355,"type": "word","value": "iPhone","element": "narrate-6-quiz-9"},
	{"index": 61,"time": 20817,"type": "word","value": "14","element": "narrate-6-quiz-9"},
	{"index": 62,"time": 21380,"type": "word","value": "pro","element": "narrate-6-quiz-9"}
]}
